---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: cnb-springboot
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: cnb-springboot
